package(default_visibility = ["//visibility:public"])

cc_library(
    name = "trace",
    srcs = [
        "simple_tracing.cpp",
        "tracing.cpp",
    ],
    hdrs = [
        "simple_tracing.h",
        "tracing.h",
    ],
    deps = [
        "@com_google_absl//absl/status:status",
    ],
)