# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: async/runtime/proto/node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='async/runtime/proto/node.proto',
  package='sss.async',
  syntax='proto3',
  serialized_options=b'\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x61sync/runtime/proto/node.proto\x12\tsss.async\"L\n\x0c\x41syncNodeDef\x12\x11\n\tfunc_name\x18\x01 \x01(\t\x12\x13\n\x0binput_names\x18\x02 \x03(\t\x12\x14\n\x0coutput_names\x18\x03 \x03(\tB\x03\xf8\x01\x01\x62\x06proto3'
)




_ASYNCNODEDEF = _descriptor.Descriptor(
  name='AsyncNodeDef',
  full_name='sss.async.AsyncNodeDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='func_name', full_name='sss.async.AsyncNodeDef.func_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_names', full_name='sss.async.AsyncNodeDef.input_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_names', full_name='sss.async.AsyncNodeDef.output_names', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['AsyncNodeDef'] = _ASYNCNODEDEF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AsyncNodeDef = _reflection.GeneratedProtocolMessageType('AsyncNodeDef', (_message.Message,), {
  'DESCRIPTOR' : _ASYNCNODEDEF,
  '__module__' : 'async.runtime.proto.node_pb2'
  # @@protoc_insertion_point(class_scope:sss.async.AsyncNodeDef)
  })
_sym_db.RegisterMessage(AsyncNodeDef)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
