package(default_visibility = ["//visibility:public"])

filegroup(
    name = "session_config",
    srcs = [
        "config.pb.txt",
    ],
)

filegroup(
    name = "graph_def",
    srcs = [
        "graph3.pb",
        "graph2.pb.txt",
    ],
)