package(default_visibility = ["//visibility:public"])
cc_binary(
    name = "hello_world",
    srcs = [
        "parallel_output_hello_world.cpp",
    ],
    deps = [
        "//async/runtime:runtime",
    ]
)