load("@com_github_grpc_grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")

package(default_visibility = ["//visibility:public"])

cc_grpc_library(
    name = "grpc_message_cc_proto",
    srcs = [
        "message.proto",
    ],
    deps = [],
)
