Import('env')
Import('libs')

build_env = env.build_env.Clone()

obj_files = ['async_value_ref.cpp', 'async_value.cpp', 'diagnostic.cpp', 'host_allocator.cpp',
            'host_buffer.cpp', 'host_context_ptr.cpp', 'host_context.cpp', 'native_function.cpp',
            'single_threaded_work_queue.cpp', 'profiled_allocator.cpp']
build_env.SmartLibrary('async_context', obj_files, LIBDEPS=['async_support', 'async_concurrent', 'LLVMSupport'])

build_env.Prepend(LIBDEPS=['async_support'])