package(default_visibility = ["//visibility:public"])

cc_test(
    name = "allocator_unittest",
    deps = [
        "//async/runtime:runtime",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "allocator_unittest.cpp",
    ],
)

cc_test(
    name = "function_ref_unittest",
    deps = [
        "//async/runtime:runtime",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "function_ref_unittest.cpp",
    ],
)

cc_test(
    name = "function_unittest",
    deps = [
        "//async/runtime:runtime",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "function_unittest.cpp",
    ],
)

cc_test(
    name = "latch_unittest",
    deps = [
        "//async/runtime:runtime",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "latch_unittest.cpp",
    ],
)

cc_test(
    name = "resource_unittest",
    deps = [
        "//async/runtime:runtime",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "resource_unittest.cpp",
    ],
)

cc_test(
    name = "string_util_unittest",
    deps = [
        "//async/runtime:runtime",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "string_util_unittest.cpp",
    ],
)

cc_test(
    name = "task_deque_unittest",
    deps = [
        "//async/runtime:runtime",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "task_deque_unittest.cpp",
    ],
)

cc_test(
    name = "task_queue_unittest",
    deps = [
        "//async/runtime:runtime",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "task_queue_unittest.cpp",
    ],
)

cc_test(
    name = "task_priority_queue_unittest",
    deps = [
        "//async/runtime:runtime",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "task_priority_queue_unittest.cpp",
    ],
)

cc_test(
    name = "test_async_speed_unittest",
    deps = [
        "//async/runtime:runtime",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "test_async_speed.cpp",
    ],
)

cc_test(
    name = "trace_unittest",
    deps = [
        "//async/trace:trace",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "trace_unittest.cpp",
    ],
)

cc_test(
    name = "unique_function_unittest",
    deps = [
        "//async/runtime:runtime",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "unique_function_unittest.cpp",
    ],
)

cc_test(
    name = "base_benchmark_test",
    deps = [
        "@com_github_google_benchmark//:benchmark_main",
    ],
    size = "small",
    srcs = [
        "base_benchmark_test.cpp"
    ],
)

cc_test(
    name = "span_unittest",
    deps = [
        "//async/support:support",
        "@com_google_googletest//:gtest",
    ],
    size = "small",
    srcs = [
        "span_unittest.cpp",
    ],
)
